// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ryzen.Shop.Catalog.Persistence;

#nullable disable

namespace Ryzen.Shop.Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20230628075438_updatePrmotions")]
    partial class updatePrmotions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("Product_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Promotions_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("Ryzen.Shop.Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("ProductID"), "Product_hilo");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PromotionID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("PromotionID");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Ryzen.Shop.Catalog.Domain.Promotion", b =>
                {
                    b.Property<int>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("PromotionID"), "Promotions_hilo");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("GetOneFree")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinimumSpendAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("SecondOneDiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("PromotionID");

                    b.HasIndex("TypeId");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("Ryzen.Shop.Catalog.Domain.PromotionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("PromotionTypes", (string)null);
                });

            modelBuilder.Entity("Ryzen.Shop.Catalog.Domain.Product", b =>
                {
                    b.HasOne("Ryzen.Shop.Catalog.Domain.Promotion", "ProductPromotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionID");

                    b.Navigation("ProductPromotion");
                });

            modelBuilder.Entity("Ryzen.Shop.Catalog.Domain.Promotion", b =>
                {
                    b.HasOne("Ryzen.Shop.Catalog.Domain.PromotionType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Ryzen.Shop.Catalog.Domain.Promotion", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
